name: Deploy Bicep file to create Azure Resources
on:
  workflow_dispatch:
    inputs:
      paramRG:
        description: 'Parameter for resource group'
        required: true
        default: 'dbr-private-rg-1'
  push:
    branches:
      - main
    
jobs:
  build-and-deploy:
    environment: Development
    runs-on: ubuntu-latest
    steps:
    - name: Print the input RG name to STDOUT
      run: echo  The tags are ${{ vars.RESOURCEGROUPNAME }} 

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: CreateRG
      run: az group create --name  ${{ vars.RESOURCEGROUPNAME }} --location 'uksouth'
    
    - name: Databricks Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        environment: Development
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ vars.RESOURCEGROUPNAME }}
        template: ./centraldeploy.bicep
        parameters: 'VMadminPassword= ${{ secrets.VM_PASSWORD_ENVSD }}'
        failOnStdErr: false


