name: Deploy Bicep file to create Azure Resources
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      VM_PASSWORD_ENVSD:
        required: true
      AZURE_CREDENTIALS:
        required: true
      RESOURCEGROUPNAME:
        required: true
  workflow_dispatch:
    inputs:
      pss:
        description: 'P'
        required: true
        default: 
  push:
    branches:
      - main
    
jobs:
  deploy:
    name: buildanddeploy
    environment: Development
    runs-on: ubuntu-latest
    steps:
    - name: Print the input RG name to STDOUT
      run: echo  The tags are ${{ vars.RESOURCEGROUPNAME }} 

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: CreateRG
      run: az group create --name  ${{ vars.RESOURCEGROUPNAME }} --location 'uksouth'
    
    - name: Databricks Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ vars.RESOURCEGROUPNAME }}
        template: ./centraldeploy.bicep
        #parameters: 'VMadminPassword= '
        failOnStdErr: false


