name: Deploy Bicep file to create Azure Resources
on:
  workflow_dispatch:
    inputs:
      paramRG:
        description: 'Parameter for resource group'
        required: true
        default: 'dbr-private-rg-1'
  push:
    branches:
      - main
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print the input RG name to STDOUT
      run: echo  The tags are ${{ inputs.paramRG }} 

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Databricks Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ inputs.paramRG }}
        template: ./main.bicep
        failOnStdErr: false

    - name: VM Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
         subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         resourceGroupName: ${{ inputs.paramRG }}
         template: ./vm.bicep
         failOnStdErr: false
