on:
    push:
      branches:
      - main
  
jobs:  
   deploy:
     uses: ./.github/workflows/AzureDeploymentResources.yml
     with:
       environment: Development
     secrets:
       VM_PASSWORD_ENVSD: ${{ secrets.VM_PASSWORD_ENVSD }}
